name: square_connect
description: A wrapper for the Square Connect APIs. It's intended use is in a flutter application to manage inventory, catalog, customers, labor, and more on the Square platform.
version: 2.0.0-dev.11
homepage: https://github.com/mtwichel/square-connect-flutter-library

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  equatable: ^2.0.3
  json_annotation: ^4.1.0
  retrofit: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.1
  retrofit_generator: ^2.0.1+1
  test: ^1.6.0
  very_good_analysis: ^2.3.0
