name: square_connect
description: A wrapper for the Square Connect APIs. It's intended use is in a flutter application to manage inventory, catalog, customers, labor, and more on the Square platform.
version: 1.1.0
homepage: https://github.com/mtwichel/square-connect-flutter-library

environment:
  sdk: ">=2.2.2 <3.0.0"

dev_dependencies:
  test: ^1.6.0

